---
- hosts: test
  remote_user: root
  vars:
    docker-compose-version: "1.24.0"
  tasks:
  - name: installing docker and git from repo
    zypper:
      name: "{{ item }}"
      state: present
    with_items:
      - git
      - docker
      - wget
      - curl

  - name: change file permission for docker-compose
    file:
      path: /usr/local/bin/docker-compose
      mode: 0755

  - name: change file permission for docker.sock
    file:
      path: /var/run/docker.sock
      mode: "a+wr"

  - name: install docker-compose
    command: 'wget https://www.github.com/docker/compose/releases/download/"{{ docker-compose-version }}"/docker-compose-$(uname -s)-$(uname -m) -O /usr/local/bin/docker-compose
'

  - name: Enable and start docker service
    service:
      enabled: yes
      name: docker
      state: started

  - name: Verify Bind ipv6 Service
    sysctl:
       name: "{{ item }}"
       value: 0
#       reload: yes
    with_items:
      - net.ipv6.bindv6only
      - net.ipv6.conf.all.forwarding


  - name: docker config setup
    copy:
      src: ./daemon.json
      dest: /etc/docker/daemon.json
#      owner: root
#      group: root
#      mode: 0644
#      backup: yes

  - name: Docker proxy setup
    copy:
      src: ./proxy.conf
      dest: /etc/systemd/system/docker.service.d/proxy.conf
#      owner: root
#      group: root
#      mode: 0644
#      backup: yes
  - name: Setup DOCKER_OPTs
    lineinfile:
      path: /etc/sysconfig/docker
      regexp: '^DOCKER_OPTS='
      line: 'DOCKER_OPTS="-H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375"'


  - name: Docker registry service setup
    copy:
      src: ./registry.service
      dest: /etc/systemd/system/registry.service
#      owner: root
#      group: root
#      mode: 0644
#      backup: yes
  - name: Enable docker registry
    service:
        name: registry
        enabled: yes
        state: started


